trigger:
- main

pr:
- main

pool:
  vmImage: 'ubuntu-latest'
  demands: Limit -equals DisableParallel 
   
variables:
  DOCKER_BUILDKIT: 1
    
steps:
- task: Bash@3
  displayName: Build all rserver images
  inputs:
    filePath: .azure/build_docker.bash
